[package]
name = "coinbase-fix50-market-data"
version = "0.1.5"
edition = "2021"
publish = false

[dependencies]
quickfix = { version = "0.1.3", path = "../../quickfix" }

[build-dependencies]
quickfix-msg-gen = { version = "0.1.3", path = "../../quickfix-msg-gen" }
