[workspace]
resolver = "2"
members = [
    "examples/coinbase-example",
    "examples/coinbase-fix-utils",
    "examples/coinbase-fix42",
    "quickfix-ffi",
    "quickfix-msg-gen",
    "quickfix-spec-parser",
    "quickfix",
    "quickfix-msg40",
    "quickfix-msg41",
    "quickfix-msg42",
    "quickfix-msg43",
    "quickfix-msg44",
]
