[package]
name = "single-order-sender"
version = "0.1.3"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.80"
chrono = "0.4.35"
parking_lot = "0.12.1"
quickfix = { path = "../../quickfix", version = "0.1.0" }
quickfix-msg44 = { path = "../../quickfix-msg44", version = "0.1.0" }
uuid = "1.7.0"
