[package]
name = "quickfix-ffi"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
cmake = "0.1.50"

[features]
default = []
print-ex = []
build-with-mysql = []
build-with-postgres = []
