[package]
name = "quickfix"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
quickfix-ffi = { path = "../quickfix-ffi" }
thiserror = "1.0.50"

[dev-dependencies]
colored = "2.0.4"

[features]
default = []
print-ex = ["quickfix-ffi/print-ex"]
