[package]
name = "coinbase-fix-utils"
version = "0.1.1"
edition = "2021"
publish = false

[dependencies]
base64 = "0.21.7"
coinbase-fix42 = { path = "../coinbase-fix42", version = "0.1.0" }
hmac = "0.12.1"
quickfix = { path = "../../quickfix", version = "0.1.0" }
sha2 = "0.10.8"
