name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: Swatinem/rust-cache@v2
  
    - name: Build
      run: cargo build --verbose
    - name: Run tests no default features
      run: cargo test --no-default-features
    - name: Run tests
      run: cargo test

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: Swatinem/rust-cache@v2

    - name: Lint
      run: cargo clippy
    - name: Format
      run: cargo fmt --check
